package com.nadi.health.ai

import com.nadi.health.ml.qwen.Sampling

/**
 * One model request: system + user text, sampler, and an output budget.
 *
 * [maxOutputChars] is a safety net, not a prompt hint — it bounds a 4B model
 * that misses its EOS (see [com.nadi.health.ml.qwen.QwenEngine]).
 */
data class AiRequest(
    val system: String,
    val user: String,
    val sampler: Sampling = Sampling.GROUNDED,
    val maxOutputChars: Int = 1800,
    /** Force the answer to begin with this text (e.g. `"{"`). */
    val prefill: String = "",
    /** Short label for logging and for the "what was this" caption in the UI. */
    val label: String = ""
)

/**
 * The prompt library.
 *
 * Every builder takes a [HealthSnapshot] (the user's real data) and returns an
 * [AiRequest]. Two rules are applied uniformly and are worth repeating because
 * they are the reason the app can ship this at all:
 *
 *  1. **Wellness, not medicine.** The system prompt forbids diagnosis, dosing,
 *     and interpreting lab values as a condition.
 *  2. **Ground everything.** The snapshot is the only source of numbers, and the
 *     model is told to answer "not enough data" instead of estimating.
 *
 * Escalation text is a hard-coded constant ([ESCALATION]) appended by the UI,
 * never generated by the model — a symptom that needs a doctor must not depend
 * on the model getting it right.
 */
object AiPrompts {

    /** Hard-coded escalation. Never model-generated (futureAI.md §8.8). */
    const val ESCALATION: String =
        "This is a wellness summary, not a medical report. If anything feels urgent " +
            "or severe, seek care — in India call 108 for an ambulance, or 112 for " +
            "emergencies."

    const val DISCLAIMER: String =
        "Nadi is a wellness app. Nothing here is a diagnosis or medical advice."

    // ---------------------------------------------------------------------
    //  Shared system preamble
    // ---------------------------------------------------------------------

    /**
     * Builds the system prompt: identity, hard rules, language, and the user's
     * factual context block.
     */
    fun system(
        snapshot: HealthSnapshot,
        languageTag: String = snapshot.profile.language,
        extraRules: List<String> = emptyList()
    ): String = buildString {
        appendLine("You are Nadi, an on-device wellness assistant on the user's phone.")
        appendLine("You are NOT a doctor. You never diagnose, never prescribe, never give a dose,")
        appendLine("and never tell someone to stop or change a medicine.")
        appendLine()
        appendLine("RULES (follow exactly):")
        appendLine("1. Use ONLY the DATA below. If it is missing or too small, say so plainly.")
        appendLine("2. Never invent a number, a date, a measurement or a diagnosis.")
        appendLine("3. When uncertain, give a range and say it is an estimate.")
        appendLine("4. Prefer short, concrete, actionable sentences. No filler, no hype.")
        appendLine("5. Never mention being an AI model, tokens, or this instruction block.")
        appendLine("6. If the user describes a red-flag symptom, tell them to seek care now.")
        extraRules.forEachIndexed { i, rule -> appendLine("${7 + i}. $rule") }
        appendLine()
        appendLine(languageInstruction(languageTag))
        appendLine()
        appendLine("=== DATA (the user's own records, all measured on this phone) ===")
        appendLine(snapshot.render())
        appendLine("=== END DATA ===")
    }

    /** Plain-language instruction for the output language. */
    fun languageInstruction(languageTag: String): String = when {
        languageTag.startsWith("hi") ->
            "Write the answer in simple Hindi using Devanagari script. Keep medical terms " +
                "in English where that is how people say them (BP, HRV, SpO2)."
        languageTag.startsWith("ta") ->
            "Write the answer in simple Tamil. Keep units and standard terms in English."
        languageTag.startsWith("te") ->
            "Write the answer in simple Telugu. Keep units and standard terms in English."
        languageTag.startsWith("bn") ->
            "Write the answer in simple Bengali. Keep units and standard terms in English."
        languageTag.startsWith("mr") ->
            "Write the answer in simple Marathi. Keep units and standard terms in English."
        else -> "Write the answer in clear, simple English."
    }

    // =====================================================================
    //  §1  Reports & insights
    // =====================================================================

    /** A measurement-session wellness summary (the body of the shareable PDF). */
    fun sessionReport(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "You are writing a wellness report the user may share with family or a doctor.",
            "Structure: a two-sentence plain summary, then sections WHAT WAS MEASURED, " +
                "WHAT CHANGED, WHAT TO WATCH, and one suggested next step.",
            "Use green/amber wording for whether each value sits inside the user's own usual range.",
            "Do not use the words diagnose, diagnosis, patient, or treatment."
        )),
        user = "Write my wellness report from the data above. Keep it under 300 words.",
        maxOutputChars = 2600,
        label = "report.session"
    )

    /**
     * Daily / weekly wellness score as JSON, so the UI can render the number in
     * a ring and show the reason separately.
     */
    fun dailyScore(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Return ONLY a JSON object, no prose, no code fence.",
            "schema: {\"score\":0-100,\"band\":\"green|amber|red\"," +
                "\"reason\":\"one short sentence\",\"components\":{\"resting_hr\":0-100," +
                "\"hrv\":0-100,\"stress\":0-100,\"activity\":0-100,\"sleep\":0-100}}",
            "Score 0-100 from the DATA only. If a component has no data, use -1 for it.",
            "Do not reward data the user has not recorded."
        )),
        user = "Score my day from the data above.",
        sampler = Sampling.PRECISE,
        maxOutputChars = 700,
        prefill = "{",
        label = "score.daily"
    )

    /** Weekly digest: what moved, in the user's own baseline terms. */
    fun weeklyDigest(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Write a weekly digest of at most 150 words as 3-5 short bullets.",
            "Each bullet must cite a direction and a magnitude from the DATA.",
            "End with exactly one practical suggestion for next week.",
            "If there is not enough history, say that in one sentence and stop."
        )),
        user = "Summarise my last 7 days against my own 30-day baseline.",
        maxOutputChars = 1400,
        label = "digest.weekly"
    )

    /** Recovery / readiness: should today be a hard day? */
    fun recoveryReadiness(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Judge readiness to train hard today from resting HR, HRV and recent training load.",
            "Start with one of: READY, MODERATE, EASY DAY.",
            "Then one sentence of why, citing the numbers you used.",
            "Then one concrete session suggestion that fits the workout types the app counts."
        )),
        user = "Am I recovered enough to train hard today?",
        maxOutputChars = 1200,
        label = "insight.readiness"
    )

    /** Lifestyle correlation hunting across the data the app actually has. */
    fun correlations(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Find at most 3 patterns that appear in the DATA.",
            "Every pattern must name the two variables and the direction, e.g. " +
                "\"on short-sleep days your resting HR ran higher\".",
            "State explicitly that these are associations in the user's own logs, not causes.",
            "If the data cannot support any pattern, say so in one sentence."
        )),
        user = "What patterns do you see between my sleep, meals, workouts and vitals?",
        maxOutputChars = 1500,
        label = "insight.correlations"
    )

    /** A compact doctor-visit card. */
    fun doctorCard(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Write a one-page snapshot a clinician can read in 30 seconds.",
            "Sections: summary line, current values with their reference band, recent changes, " +
                "current self-reported conditions and medications, and questions worth asking.",
            "Use plain language. Do not interpret lab values as a condition."
        )),
        user = "Write the doctor-visit summary card for my last 30 days.",
        maxOutputChars = 2600,
        label = "card.doctor"
    )

    // =====================================================================
    //  §2  Conversational assistant
    // =====================================================================

    /** Health-vitals Q&A grounded in the user's own history. */
    fun qa(
        snapshot: HealthSnapshot,
        question: String,
        history: List<Pair<String, String>> = emptyList()
    ): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Answer the user's question about their own readings, using only the DATA.",
            "If the DATA cannot answer it, say so in one sentence and say what to measure.",
            "Keep answers under 120 words unless the user asks to explain something."
        )),
        user = if (history.isEmpty()) question else "Question: $question",
        sampler = Sampling.varied(),
        maxOutputChars = 1600,
        label = "chat.qa"
    )

    /** Wellness glossary / explainer, in the user's language. */
    fun glossary(snapshot: HealthSnapshot, topic: String): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Explain the term in plain language for someone with no medical training.",
            "Then say, in one sentence, how it relates to the user's own data above.",
            "No jargon, no Latin, no textbook phrasing."
        )),
        user = "Explain: $topic",
        maxOutputChars = 1200,
        label = "glossary"
    )

    /** Health education on the themes that matter most in India. */
    fun education(snapshot: HealthSnapshot, topic: String): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Teach the topic in short, practical points a person can act on today.",
            "Cover the India-relevant angle (diet, climate, cost, access) where it exists.",
            "Say clearly what is a general fact and what is specific to the DATA above."
        )),
        user = "Teach me about: $topic",
        maxOutputChars = 1600,
        label = "education"
    )

    /** Turns the symptom diary into patterns — and an honest escalation. */
    fun symptomSummary(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Summarise the logged symptoms into at most 4 patterns with dates.",
            "Then list any entries that warrant seeing a doctor, and say why in one line.",
            "Never name a disease as a conclusion. Use \"worth getting checked\" phrasing.",
            "If there are no entries, say there is nothing to summarise."
        )),
        user = "Summarise my symptom journal.",
        maxOutputChars = 1500,
        label = "symptom.summary"
    )

    /** First-responder card text in the user's language. */
    fun emergencyCard(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Produce ONLY the emergency card body, with these labels on their own lines: " +
                "NAME, BLOOD GROUP, CONDITIONS, MEDICATIONS, ALLERGIES, EMERGENCY CONTACT.",
            "Copy the values verbatim from the profile. If a value is absent write \"not provided\".",
            "Do not add advice, commentary or a summary."
        )),
        user = "Write my emergency information card.",
        sampler = Sampling.PRECISE,
        maxOutputChars = 900,
        label = "card.emergency"
    )

    /** Informational medication Q&A. Never dosing. */
    fun medicationQa(snapshot: HealthSnapshot, medication: String, question: String): AiRequest =
        AiRequest(
            system = system(snapshot, extraRules = listOf(
                "Answer only what the medicine is generally used for and general " +
                    "food-timing information.",
                "NEVER give a dose, never suggest skipping, doubling or stopping a medicine, " +
                    "and always end by telling the user to confirm with their doctor or pharmacist.",
                "If unsure, say you are unsure."
            )),
            user = "Medicine: $medication\nQuestion: $question",
            maxOutputChars = 1100,
            label = "medication.qa"
        )

    /**
     * Goal-setting dialogue. [answers] is the running Q&A the UI collected, so
     * the model's job is to converge on one concrete, storable goal.
     */
    fun goalDialogue(snapshot: HealthSnapshot, answers: List<Pair<String, String>>): AiRequest =
        AiRequest(
            system = system(snapshot, extraRules = listOf(
                "Return ONLY JSON: {\"complete\":true|false,\"question\":\"…\"," +
                    "\"goal\":{\"kind\":\"weight|workout|meal|sleep|hydration|steps\"," +
                    "\"title\":\"…\",\"target\":0,\"unit\":\"…\",\"weeks\":0}}",
                "If you still need information, set complete=false and ask exactly ONE question.",
                "If you have enough, set complete=true, put a concrete measurable target, " +
                    "and leave question empty.",
                "Targets must be realistic and derived from the DATA, not aspirational."
            )),
            user = if (answers.isEmpty())
                "Start the goal-setting dialogue. Ask the one most useful first question."
            else answers.joinToString("\n") { (q, a) -> "Q: $q\nA: $a" },
            sampler = Sampling.PRECISE,
            maxOutputChars = 900,
            prefill = "{",
            label = "goal.dialogue"
        )

    // =====================================================================
    //  §3  Workout & fitness coach
    // =====================================================================

    /**
     * Weekly plan. [equipment] must be mapped onto exercises the app can
     * actually count (see [com.nadi.health.workout.ExerciseCatalog]) — the model
     * is told the allowed list so the plan is executable.
     */
    fun workoutPlan(
        snapshot: HealthSnapshot,
        goal: String,
        equipment: String,
        daysPerWeek: Int,
        minutesPerSession: Int,
        allowedExercises: List<String>
    ): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Design a weekly plan using ONLY these exercise names: " +
                allowedExercises.joinToString(", ") + ".",
            "Return ONLY JSON: {\"days\":[{\"day\":\"Mon\",\"focus\":\"…\",\"items\":" +
                "[{\"exercise\":\"…\",\"sets\":0,\"reps\":0,\"minutes\":0}],\"note\":\"…\"}]," +
                "\"why\":\"one sentence\"}",
            "Respect the user's training experience and the recovery signal in the DATA.",
            "Never prescribe a weight in kg unless the user has logged loads."
        )),
        user = "Goal: $goal. Equipment: $equipment. Days per week: $daysPerWeek. " +
            "Session length: $minutesPerSession minutes.",
        sampler = Sampling.PRECISE,
        maxOutputChars = 2200,
        prefill = "{",
        label = "plan.workout"
    )

    /** Progression suggestion for one exercise, with a plain-language why. */
    fun progression(snapshot: HealthSnapshot, exerciseName: String, recentReps: List<Int>): AiRequest =
        AiRequest(
            system = system(snapshot, extraRules = listOf(
                "Suggest the next session's target for this exercise based on the logged reps.",
                "Start with one word: PROGRESS, HOLD, or DELOAD.",
                "Then two short sentences: the target, and why, citing the reps logged.",
                "Only suggest an increase if the last two sessions were completed comfortably."
            )),
            user = "Exercise: $exerciseName\nRecent reps: ${recentReps.joinToString(", ")}",
            maxOutputChars = 900,
            label = "coach.progression"
        )

    /** Recovery-aware adjustment of a generated plan. */
    fun adaptPlanToRecovery(snapshot: HealthSnapshot, planText: String): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Adjust the given plan for today's recovery signal (HRV, resting HR, recent load).",
            "Return the adjusted plan in the same shape, plus one line explaining the change.",
            "If recovery is poor, reduce volume rather than removing the session entirely."
        )),
        user = "Current plan:\n$planText",
        maxOutputChars = 2200,
        label = "coach.recovery_adapt"
    )

    /** Run pacing coach from GPS + HR trends. */
    fun runPacing(
        snapshot: HealthSnapshot,
        distanceKm: Double,
        durationMin: Double,
        avgPaceMinPerKm: Double,
        avgHr: Double
    ): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Give pace strategy for the next run: opening pace, mid-run, and finish.",
            "Cite the user's own recent runs and heart-rate behaviour from the DATA.",
            "Three short bullets maximum, then one line on what to watch."
        )),
        user = "Last run: ${"%.2f".format(distanceKm)} km in ${"%.1f".format(durationMin)} min, " +
            "average pace ${"%.2f".format(avgPaceMinPerKm)} min/km, average HR ${avgHr.toInt()} bpm.",
        maxOutputChars = 1300,
        label = "coach.run_pacing"
    )

    /** Yoga / mobility session, measurable where the app can measure it. */
    fun yogaSession(snapshot: HealthSnapshot, minutes: Int, focus: String): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Write a guided session as a numbered list of poses with hold times.",
            "Mark any pose the app can time with the tag [TIMED] so the user can run it " +
                "in the timer; never claim the app counts yoga reps.",
            "Adapt intensity to the DATA (stress, HRV, recent training)."
        )),
        user = "$minutes-minute session focused on: $focus",
        maxOutputChars = 1800,
        label = "coach.yoga"
    )

    /** Breathing / stress session guided by the IMU respiration signal. */
    fun breathingSession(snapshot: HealthSnapshot, minutes: Int, targetBreathsPerMin: Int): AiRequest =
        AiRequest(
            system = system(snapshot, extraRules = listOf(
                "Write a paced breathwork protocol as timed steps (inhale / hold / exhale seconds).",
                "Target $targetBreathsPerMin breaths per minute.",
                "Explain in one line how the app's chest-respiration signal is used for feedback.",
                "End with one sentence on what to expect afterwards."
            )),
            user = "$minutes-minute breathing session for stress.",
            maxOutputChars = 1400,
            label = "coach.breathing"
        )

    /** Fitness-age / cardio wellness estimate. */
    fun fitnessAge(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Estimate a wellness \"fitness age\" from resting HR and running history only.",
            "Say clearly it is a motivational estimate, not a medical or VO2max measurement.",
            "State the inputs you used and how confident you are, given the DATA size."
        )),
        user = "Estimate my fitness age.",
        maxOutputChars = 1100,
        label = "insight.fitness_age"
    )

    // =====================================================================
    //  §4  Diet & nutrition (India-first)
    // =====================================================================

    /** Personalised Indian meal plan. */
    fun mealPlan(
        snapshot: HealthSnapshot,
        days: Int,
        goal: String,
        fastingPreset: String
    ): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Build the plan on everyday Indian foods the user's region and budget can supply.",
            "Respect the user's food preference strictly (vegetarian / Jain / sattvic / egg).",
            "Return ONLY JSON: {\"days\":[{\"day\":\"Mon\",\"meals\":[{\"slot\":\"breakfast\"," +
                "\"dish\":\"…\",\"protein_g\":0,\"calories\":0}],\"protein_g\":0}],\"notes\":\"…\"}",
            "No imported or expensive defaults (no quinoa, no salmon, no avocado).",
            "If the user has a condition logged, keep the suggestions in line with it, " +
                "but do not present the plan as treatment."
        )),
        user = "Plan $days days. Goal: $goal." +
            if (fastingPreset.isNotBlank()) " Fasting preset: $fastingPreset." else "",
        sampler = Sampling.PRECISE,
        maxOutputChars = 2600,
        prefill = "{",
        label = "diet.meal_plan"
    )

    /** Protein-gap readout — the chronic Indian vegetarian shortfall. */
    fun proteinGap(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Compute the protein gap from the logged meals and the user's body weight.",
            "Name the target, the intake, and the gap as numbers.",
            "Then list 4 practical Indian foods that close it, with a rough protein amount each.",
            "If no meals are logged, say so and give the target only."
        )),
        user = "Where is my protein gap?",
        maxOutputChars = 1200,
        label = "diet.protein_gap"
    )

    /** Condition-aware diet guidance (BP / diabetes / anaemia themes). */
    fun conditionDiet(snapshot: HealthSnapshot, condition: String): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Give general eating guidance for people with this condition, India-first.",
            "Never present it as treatment and never contradict a doctor's advice.",
            "End by telling the user to confirm dietary changes with their doctor or dietician.",
            "Keep it to practical foods, not nutrients."
        )),
        user = "Condition: $condition",
        maxOutputChars = 1500,
        label = "diet.condition"
    )

    /**
     * Nutrition estimate from the user's own description of a plate.
     *
     * This is the text-only fallback for §4.1: the bundled model has no vision
     * encoder, so the user describes or confirms the dish and the model
     * estimates a range. The UI labels it as an estimate the user can edit.
     */
    fun dishEstimate(snapshot: HealthSnapshot, description: String, portion: String): AiRequest =
        AiRequest(
            system = system(snapshot, extraRules = listOf(
                "Estimate nutrition for the described Indian dish and portion.",
                "Return ONLY JSON: {\"dish\":\"canonical Indian name\"," +
                    "\"calories_low\":0,\"calories_high\":0,\"protein_low\":0,\"protein_high\":0," +
                    "\"carbs_low\":0,\"carbs_high\":0,\"fat_low\":0,\"fat_high\":0," +
                    "\"confidence\":\"low|medium|high\",\"assumption\":\"one short line\"}",
                "Always give a range, never a single precise number.",
                "If the description is too vague, set confidence low and state the assumption."
            )),
            user = "Dish: $description\nPortion: $portion",
            sampler = Sampling.PRECISE,
            maxOutputChars = 900,
            prefill = "{",
            label = "diet.dish_estimate"
        )

    /**
     * Pulls the India-relevant markers out of pasted lab-report text.
     *
     * Text-only again: the user pastes or types the report body (there is no
     * OCR without a vision model). The model's only job is extraction into a
     * strict schema — no interpretation.
     */
    fun labExtraction(snapshot: HealthSnapshot, reportText: String): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Extract lab values from the pasted report text.",
            "Return ONLY JSON: {\"values\":[{\"name\":\"…\",\"value\":0,\"unit\":\"…\"," +
                "\"ref_low\":0,\"ref_high\":0}]}",
            "Copy values exactly as printed. Never round, convert or interpret.",
            "Use these preferred names when present: Hemoglobin, Fasting glucose, HbA1c, " +
                "Total cholesterol, LDL, HDL, Triglycerides, TSH, Vitamin B12, Vitamin D.",
            "If a value is absent, omit it. If nothing is parseable, return {\"values\":[]}."
        )),
        user = "REPORT TEXT:\n" + reportText.take(4000),
        sampler = Sampling.PRECISE,
        maxOutputChars = 2200,
        prefill = "{",
        label = "lab.extract"
    )

    /** Rare, measurement-backed hydration tip (never nagging — RULES.md §6). */
    fun hydrationNudge(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Decide whether a hydration nudge is actually warranted from the DATA " +
                "(heat, humidity, elevated resting HR, low logged intake).",
            "If it is not warranted, reply with exactly: NO NUDGE",
            "If it is, give one short sentence with the reason and a concrete action."
        )),
        user = "Is a hydration reminder warranted right now?",
        sampler = Sampling.PRECISE,
        maxOutputChars = 500,
        prefill = "",
        label = "diet.hydration_nudge"
    )

    // =====================================================================
    //  §5  Vision-language capabilities (gated — see VisionSupport)
    // =====================================================================

    /**
     * Lighting / framing coaching from a still image.
     *
     * Requires a vision-language model. With the text-only bundle this is never
     * called; [com.nadi.health.ai.VisionSupport] reports unavailability instead.
     */
    fun frameCoaching(snapshot: HealthSnapshot, context: String): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "You are looking at a camera frame used for a face-based heart-rate measurement.",
            "Judge ONLY lighting evenness, exposure, and whether the face is centred and steady.",
            "Give at most two short instructions. Do not comment on appearance or health."
        )),
        user = "Context: $context",
        maxOutputChars = 600,
        label = "vision.frame_coaching"
    )

    /** Food photo recognition. Requires a vision model. */
    fun foodPhoto(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Identify the Indian dish in the image and estimate macros as a range.",
            "Return ONLY JSON: {\"dish\":\"…\",\"calories_low\":0,\"calories_high\":0," +
                "\"protein_low\":0,\"protein_high\":0,\"confidence\":\"low|medium|high\"}",
            "If the image is unclear, set confidence low rather than guessing."
        )),
        user = "Identify this plate and estimate the macros.",
        sampler = Sampling.PRECISE,
        maxOutputChars = 800,
        prefill = "{",
        label = "vision.food_photo"
    )

    // =====================================================================
    //  §6  Context & environment awareness
    // =====================================================================

    /** AQI-aware outdoor advice. */
    fun airQualityAdvice(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Advise on outdoor running and breathwork for today's air quality and weather.",
            "Give a clear verdict first: GOOD TO TRAIN OUTSIDE, TRAIN INDOORS, or REST.",
            "Then two short reasons tied to the ENVIRONMENT block and the user's vitals.",
            "If there is no environment data, say so and give a general rule instead."
        )),
        user = "Should I train outside today?",
        maxOutputChars = 1000,
        label = "context.aqi"
    )

    /** Seasonal / weather-aware wellness tips. */
    fun seasonalTips(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Give 3 season- and region-appropriate wellness tips for the user's data.",
            "Tie each tip to a fact in the DATA or ENVIRONMENT block.",
            "No generic advice that would apply in any season or any country."
        )),
        user = "What should I watch for this season?",
        maxOutputChars = 1200,
        label = "context.seasonal"
    )

    /** Sleep hygiene coach — self-report first. */
    fun sleepHygiene(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Coach sleep using the self-reported hours and the vitals trends in the DATA.",
            "Nadi does not measure sleep — never imply it does.",
            "Give 3 concrete changes, ranked, each with the evidence line it comes from."
        )),
        user = "How can I sleep better?",
        maxOutputChars = 1400,
        label = "context.sleep"
    )

    // =====================================================================
    //  §7  Engagement & gamification
    // =====================================================================

    fun streakEncouragement(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Write one short encouragement line (max 25 words) grounded in the STREAKS data.",
            "No exclamation marks, no hype, no shaming. If there is no streak, " +
                "invite one small action instead."
        )),
        user = "Encourage me about my streaks.",
        maxOutputChars = 400,
        label = "engage.streak"
    )

    fun weeklyChallenge(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Propose exactly one 7-day challenge that targets a real gap in the DATA.",
            "Format: a one-line title, then why this gap, then the daily action.",
            "It must be measurable with what this app records."
        )),
        user = "Give me this week's challenge.",
        maxOutputChars = 900,
        label = "engage.challenge"
    )

    fun progressStory(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Tell the story of the user's progress in under 120 words.",
            "Use first measurement vs latest from the DATA. No invented milestones."
        )),
        user = "Write my progress story so far.",
        maxOutputChars = 1200,
        label = "engage.progress"
    )

    // =====================================================================
    //  §8  India-specific + elder care
    // =====================================================================

    /** Large-type, voice-first, simplified summary for a household elder. */
    fun elderCareSummary(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Write a very simple summary for an older reader.",
            "Short sentences. One idea per line. No numbers without a plain explanation.",
            "End with one clear action and one line telling them when to call family or a doctor."
        )),
        user = "Summarise my health simply.",
        maxOutputChars = 1100,
        label = "elder.summary"
    )

    /** Share-with-family message. */
    fun familyShareMessage(snapshot: HealthSnapshot): AiRequest = AiRequest(
        system = system(snapshot, extraRules = listOf(
            "Write a short message the user can send to family on WhatsApp.",
            "3-4 sentences, warm and factual, using only the DATA.",
            "No alarm, no diagnosis, and end with what they should do next."
        )),
        user = "Write a message to share my health update with my family.",
        maxOutputChars = 800,
        label = "family.share"
    )
}

/**
 * What the bundled model can and cannot do.
 *
 * The shipped bundle is **text-only** (`metadata.json` → `use_case: Text
 * Generation`, `config.json` → `Qwen3ForCausalLM`, no vision encoder). The
 * vision features from futureAI.md §5 therefore have no model to run on, and
 * the app says so instead of faking a result — the NPU-or-nothing rule applied
 * to capability, not just availability.
 */
object VisionSupport {

    /** True only when a vision-language bundle has been imported. */
    val hasVisionModel: Boolean = false

    const val UNAVAILABLE_MESSAGE: String =
        "This build ships the text-only Qwen3-4B bundle, so image features " +
            "(food photos, lab-report OCR, frame coaching) are switched off. " +
            "They need a Qwen3-VL bundle in the same NPU runtime — see GUIDE.md §1."
}
